/*
 * Created on 4 may 2017 ( Time 11:16:37 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.mx.portal.vo;

import java.util.Date;
 
public class AplicacionesVO{
 
    private Integer    id           ;  
    private String     descCorto    ;
    private String     descripcionaplicacion ;
    private String     urlapp       ;
    private String     parametros   ;
    private Integer    idcatalogo   ;
    private Integer    idposicionmenu ;
    private Byte       activo       ;
    private String     usuariocreacion ;
    private String     usuariomodificacion ;
    private Date       fechacreacion ;
    private Date       fechamodificacion ;
    public AplicacionesVO() {
		super();
    }
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public String getDescCorto() {
		return descCorto;
	}
	public void setDescCorto(String descCorto) {
		this.descCorto = descCorto;
	}
	public String getDescripcionaplicacion() {
		return descripcionaplicacion;
	}
	public void setDescripcionaplicacion(String descripcionaplicacion) {
		this.descripcionaplicacion = descripcionaplicacion;
	}
	public String getUrlapp() {
		return urlapp;
	}
	public void setUrlapp(String urlapp) {
		this.urlapp = urlapp;
	}
	public String getParametros() {
		return parametros;
	}
	public void setParametros(String parametros) {
		this.parametros = parametros;
	}
	public Integer getIdcatalogo() {
		return idcatalogo;
	}
	public void setIdcatalogo(Integer idcatalogo) {
		this.idcatalogo = idcatalogo;
	}
	public Integer getIdposicionmenu() {
		return idposicionmenu;
	}
	public void setIdposicionmenu(Integer idposicionmenu) {
		this.idposicionmenu = idposicionmenu;
	}
	public Byte getActivo() {
		return activo;
	}
	public void setActivo(Byte activo) {
		this.activo = activo;
	}
	public String getUsuariocreacion() {
		return usuariocreacion;
	}
	public void setUsuariocreacion(String usuariocreacion) {
		this.usuariocreacion = usuariocreacion;
	}
	public String getUsuariomodificacion() {
		return usuariomodificacion;
	}
	public void setUsuariomodificacion(String usuariomodificacion) {
		this.usuariomodificacion = usuariomodificacion;
	}
	public Date getFechacreacion() {
		return fechacreacion;
	}
	public void setFechacreacion(Date fechacreacion) {
		this.fechacreacion = fechacreacion;
	}
	public Date getFechamodificacion() {
		return fechamodificacion;
	}
	public void setFechamodificacion(Date fechamodificacion) {
		this.fechamodificacion = fechamodificacion;
	} 
}
