/*
 * Created on 7 mar 2017 ( Time 17:13:58 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.mx.portal.vo;

import java.util.Date;
import java.util.List;
 
 
public class CatalogoVO {
	private Integer    idCatalogo   ; 
    private String     descripcion  ; 
    private Byte       activo       ; 
    private String     usuariocreacion ; 
    private String     usuariomodificacion ; 
    private Date       fechacreacion ; 
    private Date       fechamodificacion ; 
    private List<CatalogoDetalleVO> listOfSwtCatalogoDetalle;
	public Integer getIdCatalogo() {
		return idCatalogo;
	}
	public void setIdCatalogo(Integer idCatalogo) {
		this.idCatalogo = idCatalogo;
	}
	public String getDescripcion() {
		return descripcion;
	}
	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}
	public Byte getActivo() {
		return activo;
	}
	public void setActivo(Byte activo) {
		this.activo = activo;
	}
	public String getUsuariocreacion() {
		return usuariocreacion;
	}
	public void setUsuariocreacion(String usuariocreacion) {
		this.usuariocreacion = usuariocreacion;
	}
	public String getUsuariomodificacion() {
		return usuariomodificacion;
	}
	public void setUsuariomodificacion(String usuariomodificacion) {
		this.usuariomodificacion = usuariomodificacion;
	}
	public Date getFechacreacion() {
		return fechacreacion;
	}
	public void setFechacreacion(Date fechacreacion) {
		this.fechacreacion = fechacreacion;
	}
	public Date getFechamodificacion() {
		return fechamodificacion;
	}
	public void setFechamodificacion(Date fechamodificacion) {
		this.fechamodificacion = fechamodificacion;
	}
	public List<CatalogoDetalleVO> getListOfSwtCatalogoDetalle() {
		return listOfSwtCatalogoDetalle;
	}
	public void setListOfSwtCatalogoDetalle(List<CatalogoDetalleVO> listOfSwtCatalogoDetalle) {
		this.listOfSwtCatalogoDetalle = listOfSwtCatalogoDetalle;
	}

}
