/*
 * Created on 4 may 2017 ( Time 11:16:37 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.mx.portal.vo;

import java.util.Date;
 
public class LogsAccesoVO{
 
    private Integer    id           ;
    private String     ippublica    ;
    private String     ipprivada    ;
    private Byte       activo       ;
    private String     usuariocreacion ;
    private String     usuariomodificacion ;
    private Date       fechacreacion ;
    private Date       fechamodificacion ;
    public LogsAccesoVO() {
		super();
    }
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public String getIppublica() {
		return ippublica;
	}
	public void setIppublica(String ippublica) {
		this.ippublica = ippublica;
	}
	public String getIpprivada() {
		return ipprivada;
	}
	public void setIpprivada(String ipprivada) {
		this.ipprivada = ipprivada;
	}
	public Byte getActivo() {
		return activo;
	}
	public void setActivo(Byte activo) {
		this.activo = activo;
	}
	public String getUsuariocreacion() {
		return usuariocreacion;
	}
	public void setUsuariocreacion(String usuariocreacion) {
		this.usuariocreacion = usuariocreacion;
	}
	public String getUsuariomodificacion() {
		return usuariomodificacion;
	}
	public void setUsuariomodificacion(String usuariomodificacion) {
		this.usuariomodificacion = usuariomodificacion;
	}
	public Date getFechacreacion() {
		return fechacreacion;
	}
	public void setFechacreacion(Date fechacreacion) {
		this.fechacreacion = fechacreacion;
	}
	public Date getFechamodificacion() {
		return fechamodificacion;
	}
	public void setFechamodificacion(Date fechamodificacion) {
		this.fechamodificacion = fechamodificacion;
	}

}
