/*
 * Created on 4 may 2017 ( Time 11:16:38 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.mx.portal.vo; 

import java.util.Date;

 
public class UsuarioVO{
    private Integer    id           ;
    private String     nombre       ; 
    private String     appaterno    ; 
    private String     apmaterno    ; 
    private String     nombrecorto  ; 
    private String     curp         ; 
    private String     contrasenia  ; 
    private Integer    vecesintentologuearse ; 
    private Integer    idcatalogo   ; 
    private Integer    intentospermitidos ; 
    private String     rfc          ; 
    private String     email        ; 
    private Integer    idcatalogocaducidad ; 
    private Integer    numdiascaducar ; 
    private Byte       activo       ; 
    private String     usuariocreacion ;
    private String     usuariomodificacion ; 
    private Date       fechacreacion ; 
    private Date       fechamodificacion ;
    public UsuarioVO() {
		super();
    }
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public String getNombre() {
		return nombre;
	}
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}
	public String getAppaterno() {
		return appaterno;
	}
	public void setAppaterno(String appaterno) {
		this.appaterno = appaterno;
	}
	public String getApmaterno() {
		return apmaterno;
	}
	public void setApmaterno(String apmaterno) {
		this.apmaterno = apmaterno;
	}
	public String getNombrecorto() {
		return nombrecorto;
	}
	public void setNombrecorto(String nombrecorto) {
		this.nombrecorto = nombrecorto;
	}
	public String getCurp() {
		return curp;
	}
	public void setCurp(String curp) {
		this.curp = curp;
	}
	public String getContrasenia() {
		return contrasenia;
	}
	public void setContrasenia(String contrasenia) {
		this.contrasenia = contrasenia;
	}
	public Integer getVecesintentologuearse() {
		return vecesintentologuearse;
	}
	public void setVecesintentologuearse(Integer vecesintentologuearse) {
		this.vecesintentologuearse = vecesintentologuearse;
	}
	public Integer getIdcatalogo() {
		return idcatalogo;
	}
	public void setIdcatalogo(Integer idcatalogo) {
		this.idcatalogo = idcatalogo;
	}
	public Integer getIntentospermitidos() {
		return intentospermitidos;
	}
	public void setIntentospermitidos(Integer intentospermitidos) {
		this.intentospermitidos = intentospermitidos;
	}
	public String getRfc() {
		return rfc;
	}
	public void setRfc(String rfc) {
		this.rfc = rfc;
	}
	public String getEmail() {
		return email;
	}
	public void setEmail(String email) {
		this.email = email;
	}
	public Integer getIdcatalogocaducidad() {
		return idcatalogocaducidad;
	}
	public void setIdcatalogocaducidad(Integer idcatalogocaducidad) {
		this.idcatalogocaducidad = idcatalogocaducidad;
	}
	public Integer getNumdiascaducar() {
		return numdiascaducar;
	}
	public void setNumdiascaducar(Integer numdiascaducar) {
		this.numdiascaducar = numdiascaducar;
	}
	public Byte getActivo() {
		return activo;
	}
	public void setActivo(Byte activo) {
		this.activo = activo;
	}
	public String getUsuariocreacion() {
		return usuariocreacion;
	}
	public void setUsuariocreacion(String usuariocreacion) {
		this.usuariocreacion = usuariocreacion;
	}
	public String getUsuariomodificacion() {
		return usuariomodificacion;
	}
	public void setUsuariomodificacion(String usuariomodificacion) {
		this.usuariomodificacion = usuariomodificacion;
	}
	public Date getFechacreacion() {
		return fechacreacion;
	}
	public void setFechacreacion(Date fechacreacion) {
		this.fechacreacion = fechacreacion;
	}
	public Date getFechamodificacion() {
		return fechamodificacion;
	}
	public void setFechamodificacion(Date fechamodificacion) {
		this.fechamodificacion = fechamodificacion;
	}
}
