/*
 * Created on 4 may 2017 ( Time 11:16:37 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.mx.portal.entity;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;
import java.util.List;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "aplicaciones"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="aplicaciones", schema="loggin", catalog="TAKEDA" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="Aplicaciones.countAll", query="SELECT COUNT(x) FROM Aplicaciones x" )
} )
public class Aplicaciones implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="desc_corto", nullable=false)
    private String     descCorto    ;

    @Column(name="descripcionaplicacion")
    private String     descripcionaplicacion ;

    @Column(name="urlapp", nullable=false)
    private String     urlapp       ;

    @Column(name="parametros", nullable=false)
    private String     parametros   ;

    @Column(name="idcatalogo", nullable=false)
    private Integer    idcatalogo   ;

    @Column(name="idposicionmenu", nullable=false)
    private Integer    idposicionmenu ;

    @Column(name="activo")
    private Byte       activo       ;

    @Column(name="usuariocreacion")
    private String     usuariocreacion ;

    @Column(name="usuariomodificacion")
    private String     usuariomodificacion ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fechacreacion")
    private Date       fechacreacion ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fechamodificacion", nullable=false)
    private Date       fechamodificacion ;

	// "idpadre" (column "idpadre") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @OneToMany(mappedBy="aplicaciones", targetEntity=Excepciones.class)
    private List<Excepciones> listOfExcepciones;

    @OneToMany(mappedBy="aplicaciones", targetEntity=Aplicaciones.class)
    private List<Aplicaciones> listOfAplicaciones;

    @OneToMany(mappedBy="aplicaciones", targetEntity=LogsAcceso.class)
    private List<LogsAcceso> listOfLogsAcceso;

    @OneToMany(mappedBy="aplicaciones", targetEntity=Permisos.class)
    private List<Permisos> listOfPermisos;

    @ManyToOne
    @JoinColumn(name="idpadre", referencedColumnName="id")
    private Aplicaciones aplicaciones;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Aplicaciones() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : desc_corto ( nvarchar ) 
    public void setDescCorto( String descCorto ) {
        this.descCorto = descCorto;
    }
    public String getDescCorto() {
        return this.descCorto;
    }

    //--- DATABASE MAPPING : descripcionaplicacion ( nvarchar ) 
    public void setDescripcionaplicacion( String descripcionaplicacion ) {
        this.descripcionaplicacion = descripcionaplicacion;
    }
    public String getDescripcionaplicacion() {
        return this.descripcionaplicacion;
    }

    //--- DATABASE MAPPING : urlapp ( nvarchar ) 
    public void setUrlapp( String urlapp ) {
        this.urlapp = urlapp;
    }
    public String getUrlapp() {
        return this.urlapp;
    }

    //--- DATABASE MAPPING : parametros ( nvarchar ) 
    public void setParametros( String parametros ) {
        this.parametros = parametros;
    }
    public String getParametros() {
        return this.parametros;
    }

    //--- DATABASE MAPPING : idcatalogo ( int ) 
    public void setIdcatalogo( Integer idcatalogo ) {
        this.idcatalogo = idcatalogo;
    }
    public Integer getIdcatalogo() {
        return this.idcatalogo;
    }

    //--- DATABASE MAPPING : idposicionmenu ( int ) 
    public void setIdposicionmenu( Integer idposicionmenu ) {
        this.idposicionmenu = idposicionmenu;
    }
    public Integer getIdposicionmenu() {
        return this.idposicionmenu;
    }

    //--- DATABASE MAPPING : activo ( tinyint ) 
    public void setActivo( Byte activo ) {
        this.activo = activo;
    }
    public Byte getActivo() {
        return this.activo;
    }

    //--- DATABASE MAPPING : usuariocreacion ( nvarchar ) 
    public void setUsuariocreacion( String usuariocreacion ) {
        this.usuariocreacion = usuariocreacion;
    }
    public String getUsuariocreacion() {
        return this.usuariocreacion;
    }

    //--- DATABASE MAPPING : usuariomodificacion ( nvarchar ) 
    public void setUsuariomodificacion( String usuariomodificacion ) {
        this.usuariomodificacion = usuariomodificacion;
    }
    public String getUsuariomodificacion() {
        return this.usuariomodificacion;
    }

    //--- DATABASE MAPPING : fechacreacion ( datetime ) 
    public void setFechacreacion( Date fechacreacion ) {
        this.fechacreacion = fechacreacion;
    }
    public Date getFechacreacion() {
        return this.fechacreacion;
    }

    //--- DATABASE MAPPING : fechamodificacion ( datetime ) 
    public void setFechamodificacion( Date fechamodificacion ) {
        this.fechamodificacion = fechamodificacion;
    }
    public Date getFechamodificacion() {
        return this.fechamodificacion;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setListOfExcepciones( List<Excepciones> listOfExcepciones ) {
        this.listOfExcepciones = listOfExcepciones;
    }
    public List<Excepciones> getListOfExcepciones() {
        return this.listOfExcepciones;
    }

    public void setListOfAplicaciones( List<Aplicaciones> listOfAplicaciones ) {
        this.listOfAplicaciones = listOfAplicaciones;
    }
    public List<Aplicaciones> getListOfAplicaciones() {
        return this.listOfAplicaciones;
    }

    public void setListOfLogsAcceso( List<LogsAcceso> listOfLogsAcceso ) {
        this.listOfLogsAcceso = listOfLogsAcceso;
    }
    public List<LogsAcceso> getListOfLogsAcceso() {
        return this.listOfLogsAcceso;
    }

    public void setListOfPermisos( List<Permisos> listOfPermisos ) {
        this.listOfPermisos = listOfPermisos;
    }
    public List<Permisos> getListOfPermisos() {
        return this.listOfPermisos;
    }

    public void setAplicaciones( Aplicaciones aplicaciones ) {
        this.aplicaciones = aplicaciones;
    }
    public Aplicaciones getAplicaciones() {
        return this.aplicaciones;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(descCorto);
        sb.append("|");
        sb.append(descripcionaplicacion);
        sb.append("|");
        sb.append(urlapp);
        sb.append("|");
        sb.append(parametros);
        sb.append("|");
        sb.append(idcatalogo);
        sb.append("|");
        sb.append(idposicionmenu);
        sb.append("|");
        sb.append(activo);
        sb.append("|");
        sb.append(usuariocreacion);
        sb.append("|");
        sb.append(usuariomodificacion);
        sb.append("|");
        sb.append(fechacreacion);
        sb.append("|");
        sb.append(fechamodificacion);
        return sb.toString(); 
    } 

}
