/*
 * Created on 4 may 2017 ( Time 11:16:37 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.mx.portal.entity;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;
import java.util.List;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "catalogo"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="catalogo", schema="loggin", catalog="TAKEDA" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="Catalogo.countAll", query="SELECT COUNT(x) FROM Catalogo x" )
} )
public class Catalogo implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id_catalogo", nullable=false)
    private Integer    idCatalogo   ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="descripcion")
    private String     descripcion  ;

    @Column(name="activo")
    private Byte       activo       ;

    @Column(name="usuariocreacion", nullable=false)
    private String     usuariocreacion ;

    @Column(name="usuariomodificacion")
    private String     usuariomodificacion ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fechacreacion", nullable=false)
    private Date       fechacreacion ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fechamodificacion", nullable=false)
    private Date       fechamodificacion ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @OneToMany(mappedBy="catalogo", targetEntity=CatalogoDetalle.class)
    private List<CatalogoDetalle> listOfCatalogoDetalle;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Catalogo() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setIdCatalogo( Integer idCatalogo ) {
        this.idCatalogo = idCatalogo ;
    }
    public Integer getIdCatalogo() {
        return this.idCatalogo;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : descripcion ( nvarchar ) 
    public void setDescripcion( String descripcion ) {
        this.descripcion = descripcion;
    }
    public String getDescripcion() {
        return this.descripcion;
    }

    //--- DATABASE MAPPING : activo ( tinyint ) 
    public void setActivo( Byte activo ) {
        this.activo = activo;
    }
    public Byte getActivo() {
        return this.activo;
    }

    //--- DATABASE MAPPING : usuariocreacion ( nvarchar ) 
    public void setUsuariocreacion( String usuariocreacion ) {
        this.usuariocreacion = usuariocreacion;
    }
    public String getUsuariocreacion() {
        return this.usuariocreacion;
    }

    //--- DATABASE MAPPING : usuariomodificacion ( nvarchar ) 
    public void setUsuariomodificacion( String usuariomodificacion ) {
        this.usuariomodificacion = usuariomodificacion;
    }
    public String getUsuariomodificacion() {
        return this.usuariomodificacion;
    }

    //--- DATABASE MAPPING : fechacreacion ( datetime ) 
    public void setFechacreacion( Date fechacreacion ) {
        this.fechacreacion = fechacreacion;
    }
    public Date getFechacreacion() {
        return this.fechacreacion;
    }

    //--- DATABASE MAPPING : fechamodificacion ( datetime ) 
    public void setFechamodificacion( Date fechamodificacion ) {
        this.fechamodificacion = fechamodificacion;
    }
    public Date getFechamodificacion() {
        return this.fechamodificacion;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setListOfCatalogoDetalle( List<CatalogoDetalle> listOfCatalogoDetalle ) {
        this.listOfCatalogoDetalle = listOfCatalogoDetalle;
    }
    public List<CatalogoDetalle> getListOfCatalogoDetalle() {
        return this.listOfCatalogoDetalle;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(idCatalogo);
        sb.append("]:"); 
        sb.append(descripcion);
        sb.append("|");
        sb.append(activo);
        sb.append("|");
        sb.append(usuariocreacion);
        sb.append("|");
        sb.append(usuariomodificacion);
        sb.append("|");
        sb.append(fechacreacion);
        sb.append("|");
        sb.append(fechamodificacion);
        return sb.toString(); 
    } 

}
