/*
 * Created on 4 may 2017 ( Time 11:16:37 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.mx.portal.entity;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;
import java.util.List;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "rol"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="rol", schema="loggin", catalog="TAKEDA" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="Rol.countAll", query="SELECT COUNT(x) FROM Rol x" )
} )
public class Rol implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="prioridad", nullable=false)
    private Integer    prioridad    ;

    @Column(name="descripcioncorto", nullable=false)
    private String     descripcioncorto ;

    @Column(name="descripcionlargo")
    private String     descripcionlargo ;

    @Column(name="activo")
    private Byte       activo       ;

    @Column(name="usuariocreacion")
    private String     usuariocreacion ;

    @Column(name="usuariomodificacion")
    private String     usuariomodificacion ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fechacreacion")
    private Date       fechacreacion ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fechamodificacion", nullable=false)
    private Date       fechamodificacion ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @OneToMany(mappedBy="rol", targetEntity=Permisos.class)
    private List<Permisos> listOfPermisos;

    @OneToMany(mappedBy="rol", targetEntity=Usuario.class)
    private List<Usuario> listOfUsuario;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Rol() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : prioridad ( int ) 
    public void setPrioridad( Integer prioridad ) {
        this.prioridad = prioridad;
    }
    public Integer getPrioridad() {
        return this.prioridad;
    }

    //--- DATABASE MAPPING : descripcioncorto ( nvarchar ) 
    public void setDescripcioncorto( String descripcioncorto ) {
        this.descripcioncorto = descripcioncorto;
    }
    public String getDescripcioncorto() {
        return this.descripcioncorto;
    }

    //--- DATABASE MAPPING : descripcionlargo ( nvarchar ) 
    public void setDescripcionlargo( String descripcionlargo ) {
        this.descripcionlargo = descripcionlargo;
    }
    public String getDescripcionlargo() {
        return this.descripcionlargo;
    }

    //--- DATABASE MAPPING : activo ( tinyint ) 
    public void setActivo( Byte activo ) {
        this.activo = activo;
    }
    public Byte getActivo() {
        return this.activo;
    }

    //--- DATABASE MAPPING : usuariocreacion ( nvarchar ) 
    public void setUsuariocreacion( String usuariocreacion ) {
        this.usuariocreacion = usuariocreacion;
    }
    public String getUsuariocreacion() {
        return this.usuariocreacion;
    }

    //--- DATABASE MAPPING : usuariomodificacion ( nvarchar ) 
    public void setUsuariomodificacion( String usuariomodificacion ) {
        this.usuariomodificacion = usuariomodificacion;
    }
    public String getUsuariomodificacion() {
        return this.usuariomodificacion;
    }

    //--- DATABASE MAPPING : fechacreacion ( datetime ) 
    public void setFechacreacion( Date fechacreacion ) {
        this.fechacreacion = fechacreacion;
    }
    public Date getFechacreacion() {
        return this.fechacreacion;
    }

    //--- DATABASE MAPPING : fechamodificacion ( datetime ) 
    public void setFechamodificacion( Date fechamodificacion ) {
        this.fechamodificacion = fechamodificacion;
    }
    public Date getFechamodificacion() {
        return this.fechamodificacion;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setListOfPermisos( List<Permisos> listOfPermisos ) {
        this.listOfPermisos = listOfPermisos;
    }
    public List<Permisos> getListOfPermisos() {
        return this.listOfPermisos;
    }

    public void setListOfUsuario( List<Usuario> listOfUsuario ) {
        this.listOfUsuario = listOfUsuario;
    }
    public List<Usuario> getListOfUsuario() {
        return this.listOfUsuario;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(prioridad);
        sb.append("|");
        sb.append(descripcioncorto);
        sb.append("|");
        sb.append(descripcionlargo);
        sb.append("|");
        sb.append(activo);
        sb.append("|");
        sb.append(usuariocreacion);
        sb.append("|");
        sb.append(usuariomodificacion);
        sb.append("|");
        sb.append(fechacreacion);
        sb.append("|");
        sb.append(fechamodificacion);
        return sb.toString(); 
    } 

}
